// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin_accounts
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAccount = `-- name: CreateAdminAccount :one

INSERT INTO admin_accounts (email, name, role, password_hash, totp_secret_enc, totp_enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, name, role, password_hash, totp_secret_enc, totp_enabled, created_by, last_active_at, disabled_at, created_at
`

type CreateAdminAccountParams struct {
	Email         string
	Name          string
	Role          string
	PasswordHash  string
	TotpSecretEnc []byte
	TotpEnabled   bool
	CreatedBy     *int64
}

// 平台管理员。与 users 完全独立的一套（ARCHITECTURE.md §4.5）。
func (q *Queries) CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, createAdminAccount,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.TotpSecretEnc,
		arg.TotpEnabled,
		arg.CreatedBy,
	)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedBy,
		&i.LastActiveAt,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (token_hash, admin_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_hash, admin_id, expires_at, ip, user_agent, revoked_at, created_at
`

type CreateAdminSessionParams struct {
	TokenHash []byte
	AdminID   int64
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.TokenHash,
		arg.AdminID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AdminID,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const disableAdmin = `-- name: DisableAdmin :exec
UPDATE admin_accounts SET disabled_at = now() WHERE id = $1 AND disabled_at IS NULL
`

// 停用而非删除：审计日志里的 actor 要能一直解析出人名。
func (q *Queries) DisableAdmin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableAdmin, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, name, role, password_hash, totp_secret_enc, totp_enabled, created_by, last_active_at, disabled_at, created_at FROM admin_accounts WHERE lower(email) = lower($1)
`

func (q *Queries) GetAdminByEmail(ctx context.Context, lower string) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, lower)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedBy,
		&i.LastActiveAt,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, name, role, password_hash, totp_secret_enc, totp_enabled, created_by, last_active_at, disabled_at, created_at FROM admin_accounts WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedBy,
		&i.LastActiveAt,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminSessionByTokenHash = `-- name: GetAdminSessionByTokenHash :one
SELECT s.id, s.token_hash, s.admin_id, s.expires_at, s.revoked_at, s.created_at,
       a.email, a.name, a.role, a.totp_enabled, a.disabled_at
FROM admin_sessions s
JOIN admin_accounts a ON a.id = s.admin_id
WHERE s.token_hash = $1
`

type GetAdminSessionByTokenHashRow struct {
	ID          int64
	TokenHash   []byte
	AdminID     int64
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
	Email       string
	Name        string
	Role        string
	TotpEnabled bool
	DisabledAt  *time.Time
}

func (q *Queries) GetAdminSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAdminSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByTokenHash, tokenHash)
	var i GetAdminSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AdminID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.TotpEnabled,
		&i.DisabledAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (actor_kind, actor_id, actor_label, action, target, destructive, detail, ip, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, actor_kind, actor_id, actor_label, action, target, destructive, detail, ip, request_id, created_at
`

type InsertAuditLogParams struct {
	ActorKind   string
	ActorID     *int64
	ActorLabel  string
	Action      string
	Target      string
	Destructive bool
	Detail      []byte
	Ip          *netip.Addr
	RequestID   *string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorLabel,
		arg.Action,
		arg.Target,
		arg.Destructive,
		arg.Detail,
		arg.Ip,
		arg.RequestID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorKind,
		&i.ActorID,
		&i.ActorLabel,
		&i.Action,
		&i.Target,
		&i.Destructive,
		&i.Detail,
		&i.Ip,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, name, role, password_hash, totp_secret_enc, totp_enabled, created_by, last_active_at, disabled_at, created_at FROM admin_accounts ORDER BY created_at
`

func (q *Queries) ListAdmins(ctx context.Context) ([]AdminAccount, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAccount{}
	for rows.Next() {
		var i AdminAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.CreatedBy,
			&i.LastActiveAt,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_kind, actor_id, actor_label, action, target, destructive, detail, ip, request_id, created_at FROM audit_logs
WHERE (NOT $1::boolean OR destructive)
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditLogsParams struct {
	DestructiveOnly bool
	RowLimit        int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.DestructiveOnly, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorKind,
			&i.ActorID,
			&i.ActorLabel,
			&i.Action,
			&i.Target,
			&i.Destructive,
			&i.Detail,
			&i.Ip,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAdminSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, tokenHash)
	return err
}

const revokeAllAdminSessions = `-- name: RevokeAllAdminSessions :exec
UPDATE admin_sessions SET revoked_at = now() WHERE admin_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAdminSessions(ctx context.Context, adminID int64) error {
	_, err := q.db.Exec(ctx, revokeAllAdminSessions, adminID)
	return err
}

const setAdminTOTP = `-- name: SetAdminTOTP :exec
UPDATE admin_accounts SET totp_secret_enc = $2, totp_enabled = $3 WHERE id = $1
`

type SetAdminTOTPParams struct {
	ID            int64
	TotpSecretEnc []byte
	TotpEnabled   bool
}

func (q *Queries) SetAdminTOTP(ctx context.Context, arg SetAdminTOTPParams) error {
	_, err := q.db.Exec(ctx, setAdminTOTP, arg.ID, arg.TotpSecretEnc, arg.TotpEnabled)
	return err
}

const touchAdminActivity = `-- name: TouchAdminActivity :exec
UPDATE admin_accounts SET last_active_at = now() WHERE id = $1
`

func (q *Queries) TouchAdminActivity(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAdminActivity, id)
	return err
}
