// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: catalog.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogCounts = `-- name: CatalogCounts :one
SELECT
    (SELECT count(*) FROM models WHERE status = 'listed')                    AS model_count,
    (SELECT count(DISTINCT provider_id) FROM models WHERE status = 'listed') AS provider_count,
    (SELECT coalesce(sum(tokens), 0)::bigint FROM model_stats
      WHERE day >= (current_date - 30))                                      AS monthly_tokens,
    -- 网关 p50：按 tokens 加权平均。B3 之前 model_stats 是空的，
    -- 这里返回 NULL 而不是 0——**没有遥测**与**零延迟**必须能区分。
    (SELECT to_jsonb(sum(p50_latency_ms * tokens) / nullif(sum(tokens), 0))
       FROM model_stats WHERE day >= (current_date - 7)
        AND p50_latency_ms IS NOT NULL)                                      AS gateway_latency_ms_p50,
    (SELECT to_jsonb(max(day)) FROM model_stats)                             AS stats_updated_at
`

type CatalogCountsRow struct {
	ModelCount          int64
	ProviderCount       int64
	MonthlyTokens       int64
	GatewayLatencyMsP50 []byte
	StatsUpdatedAt      []byte
}

func (q *Queries) CatalogCounts(ctx context.Context) (CatalogCountsRow, error) {
	row := q.db.QueryRow(ctx, catalogCounts)
	var i CatalogCountsRow
	err := row.Scan(
		&i.ModelCount,
		&i.ProviderCount,
		&i.MonthlyTokens,
		&i.GatewayLatencyMsP50,
		&i.StatsUpdatedAt,
	)
	return i, err
}

const getBenchmarkBySlug = `-- name: GetBenchmarkBySlug :one
SELECT b.id, b.slug, b.name, b.category, b.description, b.methodology,
       b.configuration, b.run_count, b.last_run_at,
       (SELECT count(*) FROM benchmark_results r WHERE r.benchmark_id = b.id) AS evaluated_model_count
FROM benchmarks b WHERE b.slug = $1
`

type GetBenchmarkBySlugRow struct {
	ID                  int64
	Slug                string
	Name                string
	Category            string
	Description         string
	Methodology         string
	Configuration       []byte
	RunCount            int32
	LastRunAt           *time.Time
	EvaluatedModelCount int64
}

func (q *Queries) GetBenchmarkBySlug(ctx context.Context, slug string) (GetBenchmarkBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBenchmarkBySlug, slug)
	var i GetBenchmarkBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Methodology,
		&i.Configuration,
		&i.RunCount,
		&i.LastRunAt,
		&i.EvaluatedModelCount,
	)
	return i, err
}

const getDocsPage = `-- name: GetDocsPage :one
SELECT slug, title, description, body_markdown, updated_at
FROM docs_pages WHERE slug = $1
`

type GetDocsPageRow struct {
	Slug         string
	Title        string
	Description  string
	BodyMarkdown string
	UpdatedAt    time.Time
}

func (q *Queries) GetDocsPage(ctx context.Context, slug string) (GetDocsPageRow, error) {
	row := q.db.QueryRow(ctx, getDocsPage, slug)
	var i GetDocsPageRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.BodyMarkdown,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelByPath = `-- name: GetModelByPath :one
SELECT
    m.id, m.slug, m.display_name, m.description, m.logo_url,
    m.modalities, m.capabilities, m.context_length, m.max_output_tokens,
    m.architecture, m.input_formats, m.output_formats, m.supported_parameters,
    m.zero_data_retention, m.hosting, m.billing_model, m.status,
    m.quality_score, m.released_at,
    p.id AS provider_id, p.slug AS provider_slug, p.name AS provider_name,
    p.logo_url AS provider_logo_url,
    (SELECT count(*) FROM models pm
      WHERE pm.provider_id = p.id AND pm.status = 'listed') AS provider_model_count,
    to_jsonb(pr) AS price_version, to_jsonb(st) AS stats
FROM models m
JOIN providers p ON p.id = m.provider_id
LEFT JOIN LATERAL (
    SELECT mp.id, mp.rates, mp.currency, mp.effective_from
    FROM model_prices mp
    WHERE mp.id = pricing_effective_version(m.billing_model, 'default', NULL, now())
) pr ON true
LEFT JOIN LATERAL (
    SELECT coalesce(sum(s.tokens), 0)::bigint AS tokens_30d,
           max(s.throughput_tokens_per_second) AS throughput
    FROM model_stats s
    WHERE s.model_id = m.id AND s.day >= (current_date - 30)
) st ON true
WHERE p.slug = $1 AND m.slug = $2 AND m.status = 'listed'
`

type GetModelByPathParams struct {
	ProviderSlug string
	ModelSlug    string
}

type GetModelByPathRow struct {
	ID                  int64
	Slug                string
	DisplayName         string
	Description         string
	LogoUrl             string
	Modalities          []string
	Capabilities        []string
	ContextLength       *int32
	MaxOutputTokens     *int32
	Architecture        *string
	InputFormats        []string
	OutputFormats       []string
	SupportedParameters []string
	ZeroDataRetention   bool
	Hosting             string
	BillingModel        string
	Status              string
	QualityScore        pgtype.Numeric
	ReleasedAt          time.Time
	ProviderID          int64
	ProviderSlug        string
	ProviderName        string
	ProviderLogoUrl     string
	ProviderModelCount  int64
	PriceVersion        []byte
	Stats               []byte
}

// 详情页。与 ListModels 取价格的方式**必须一致**——同一个函数，同一个 scope。
func (q *Queries) GetModelByPath(ctx context.Context, arg GetModelByPathParams) (GetModelByPathRow, error) {
	row := q.db.QueryRow(ctx, getModelByPath, arg.ProviderSlug, arg.ModelSlug)
	var i GetModelByPathRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LogoUrl,
		&i.Modalities,
		&i.Capabilities,
		&i.ContextLength,
		&i.MaxOutputTokens,
		&i.Architecture,
		&i.InputFormats,
		&i.OutputFormats,
		&i.SupportedParameters,
		&i.ZeroDataRetention,
		&i.Hosting,
		&i.BillingModel,
		&i.Status,
		&i.QualityScore,
		&i.ReleasedAt,
		&i.ProviderID,
		&i.ProviderSlug,
		&i.ProviderName,
		&i.ProviderLogoUrl,
		&i.ProviderModelCount,
		&i.PriceVersion,
		&i.Stats,
	)
	return i, err
}

const listBenchmarkResults = `-- name: ListBenchmarkResults :many
SELECT r.benchmark_id, r.model_id, r.score, r.percentile, r.cost_nano,
       r.duration_ms, r.sample_count,
       rank() OVER (PARTITION BY r.benchmark_id ORDER BY r.score DESC) AS rank
FROM benchmark_results r
WHERE r.benchmark_id = ANY($1::bigint[])
ORDER BY r.benchmark_id, r.score DESC
`

type ListBenchmarkResultsRow struct {
	BenchmarkID int64
	ModelID     int64
	Score       pgtype.Numeric
	Percentile  pgtype.Numeric
	CostNano    int64
	DurationMs  pgtype.Numeric
	SampleCount int32
	Rank        int64
}

// rank 在查询里算：让 Go 侧再排一遍等于给"两处排序不一致"留位置。
func (q *Queries) ListBenchmarkResults(ctx context.Context, benchmarkIds []int64) ([]ListBenchmarkResultsRow, error) {
	rows, err := q.db.Query(ctx, listBenchmarkResults, benchmarkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBenchmarkResultsRow{}
	for rows.Next() {
		var i ListBenchmarkResultsRow
		if err := rows.Scan(
			&i.BenchmarkID,
			&i.ModelID,
			&i.Score,
			&i.Percentile,
			&i.CostNano,
			&i.DurationMs,
			&i.SampleCount,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenchmarks = `-- name: ListBenchmarks :many

SELECT b.id, b.slug, b.name, b.category, b.description, b.run_count, b.last_run_at,
       (SELECT count(*) FROM benchmark_results r WHERE r.benchmark_id = b.id) AS evaluated_model_count
FROM benchmarks b
WHERE $1::text IS NULL OR b.category = $1
ORDER BY b.name
`

type ListBenchmarksRow struct {
	ID                  int64
	Slug                string
	Name                string
	Category            string
	Description         string
	RunCount            int32
	LastRunAt           *time.Time
	EvaluatedModelCount int64
}

// ── 评测 ──────────────────────────────────────────────────────
func (q *Queries) ListBenchmarks(ctx context.Context, category *string) ([]ListBenchmarksRow, error) {
	rows, err := q.db.Query(ctx, listBenchmarks, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBenchmarksRow{}
	for rows.Next() {
		var i ListBenchmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.RunCount,
			&i.LastRunAt,
			&i.EvaluatedModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsNavigation = `-- name: ListDocsNavigation :many

SELECT slug, group_title, group_position, title, badge
FROM docs_pages ORDER BY group_position, position, title
`

type ListDocsNavigationRow struct {
	Slug          string
	GroupTitle    string
	GroupPosition int32
	Title         string
	Badge         string
}

// ── 文档 ──────────────────────────────────────────────────────
func (q *Queries) ListDocsNavigation(ctx context.Context) ([]ListDocsNavigationRow, error) {
	rows, err := q.db.Query(ctx, listDocsNavigation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsNavigationRow{}
	for rows.Next() {
		var i ListDocsNavigationRow
		if err := rows.Scan(
			&i.Slug,
			&i.GroupTitle,
			&i.GroupPosition,
			&i.Title,
			&i.Badge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedModelIDs = `-- name: ListFeaturedModelIDs :many
SELECT id FROM models
WHERE status = 'listed' AND featured
ORDER BY featured_rank NULLS LAST, released_at DESC
LIMIT $1::int
`

func (q *Queries) ListFeaturedModelIDs(ctx context.Context, rowLimit int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFeaturedModelIDs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelActivity = `-- name: ListModelActivity :many
SELECT id, type, title, occurred_at FROM model_activity
WHERE model_id = $1 ORDER BY occurred_at DESC LIMIT $2::int
`

type ListModelActivityParams struct {
	ModelID  int64
	RowLimit int32
}

type ListModelActivityRow struct {
	ID         int64
	Type       string
	Title      string
	OccurredAt time.Time
}

func (q *Queries) ListModelActivity(ctx context.Context, arg ListModelActivityParams) ([]ListModelActivityRow, error) {
	rows, err := q.db.Query(ctx, listModelActivity, arg.ModelID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelActivityRow{}
	for rows.Next() {
		var i ListModelActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelBenchmarkScores = `-- name: ListModelBenchmarkScores :many
SELECT b.slug AS benchmark_slug, b.name AS benchmark_name, r.score, r.percentile
FROM benchmark_results r
JOIN benchmarks b ON b.id = r.benchmark_id
WHERE r.model_id = $1
ORDER BY b.name
`

type ListModelBenchmarkScoresRow struct {
	BenchmarkSlug string
	BenchmarkName string
	Score         pgtype.Numeric
	Percentile    pgtype.Numeric
}

func (q *Queries) ListModelBenchmarkScores(ctx context.Context, modelID int64) ([]ListModelBenchmarkScoresRow, error) {
	rows, err := q.db.Query(ctx, listModelBenchmarkScores, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelBenchmarkScoresRow{}
	for rows.Next() {
		var i ListModelBenchmarkScoresRow
		if err := rows.Scan(
			&i.BenchmarkSlug,
			&i.BenchmarkName,
			&i.Score,
			&i.Percentile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelFAQ = `-- name: ListModelFAQ :many
SELECT question, answer FROM model_faq WHERE model_id = $1 ORDER BY position, id
`

type ListModelFAQRow struct {
	Question string
	Answer   string
}

func (q *Queries) ListModelFAQ(ctx context.Context, modelID int64) ([]ListModelFAQRow, error) {
	rows, err := q.db.Query(ctx, listModelFAQ, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelFAQRow{}
	for rows.Next() {
		var i ListModelFAQRow
		if err := rows.Scan(&i.Question, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelSummariesByIDs = `-- name: ListModelSummariesByIDs :many
SELECT
    m.id, m.slug, m.display_name, m.description, m.logo_url,
    m.modalities, m.capabilities, m.context_length, m.quality_score,
    m.released_at, m.billing_model, m.hosting,
    p.id AS provider_id, p.slug AS provider_slug, p.name AS provider_name,
    p.logo_url AS provider_logo_url,
    (SELECT count(*) FROM models pm
      WHERE pm.provider_id = p.id AND pm.status = 'listed') AS provider_model_count,
    to_jsonb(pr) AS price_version, to_jsonb(st) AS stats
FROM models m
JOIN providers p ON p.id = m.provider_id
LEFT JOIN LATERAL (
    SELECT mp.id, mp.rates, mp.currency, mp.effective_from
    FROM model_prices mp
    WHERE mp.id = pricing_effective_version(m.billing_model, 'default', NULL, now())
) pr ON true
LEFT JOIN LATERAL (
    SELECT coalesce(sum(s.tokens), 0)::bigint AS tokens_30d,
           max(s.throughput_tokens_per_second) AS throughput
    FROM model_stats s
    WHERE s.model_id = m.id AND s.day >= (current_date - 30)
) st ON true
WHERE m.id = ANY($1::bigint[]) AND m.status = 'listed'
`

type ListModelSummariesByIDsRow struct {
	ID                 int64
	Slug               string
	DisplayName        string
	Description        string
	LogoUrl            string
	Modalities         []string
	Capabilities       []string
	ContextLength      *int32
	QualityScore       pgtype.Numeric
	ReleasedAt         time.Time
	BillingModel       string
	Hosting            string
	ProviderID         int64
	ProviderSlug       string
	ProviderName       string
	ProviderLogoUrl    string
	ProviderModelCount int64
	PriceVersion       []byte
	Stats              []byte
}

// 精选模型、评测优胜者、榜单条目、相关模型都要嵌一个 ModelSummary。
// 走同一个查询，避免"首页的价格"与"列表页的价格"各查各的。
func (q *Queries) ListModelSummariesByIDs(ctx context.Context, ids []int64) ([]ListModelSummariesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listModelSummariesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelSummariesByIDsRow{}
	for rows.Next() {
		var i ListModelSummariesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.LogoUrl,
			&i.Modalities,
			&i.Capabilities,
			&i.ContextLength,
			&i.QualityScore,
			&i.ReleasedAt,
			&i.BillingModel,
			&i.Hosting,
			&i.ProviderID,
			&i.ProviderSlug,
			&i.ProviderName,
			&i.ProviderLogoUrl,
			&i.ProviderModelCount,
			&i.PriceVersion,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many

WITH params AS (
    SELECT CASE WHEN $4::text = 'asc' THEN 1 ELSE -1 END AS dir
), base AS (
    SELECT
        m.id,
        m.slug,
        m.display_name,
        m.description,
        m.logo_url,
        m.modalities,
        m.capabilities,
        m.context_length,
        m.quality_score,
        m.released_at,
        m.billing_model,
        m.hosting,
        p.id       AS provider_id,
        p.slug     AS provider_slug,
        p.name     AS provider_name,
        p.logo_url AS provider_logo_url,
        (SELECT count(*) FROM models pm
          WHERE pm.provider_id = p.id AND pm.status = 'listed') AS provider_model_count,
        to_jsonb(pr) AS price_version,
        to_jsonb(st) AS stats,
        params.dir,
        CASE $5::text
            WHEN 'price'      THEN (pr.rates -> 'input' ->> 'per_million_nano')::double precision
            WHEN 'throughput' THEN st.throughput::double precision
            WHEN 'usage'      THEN st.tokens_30d::double precision
            ELSE extract(epoch FROM m.released_at)
        END AS raw_key
    FROM models m
    JOIN providers p ON p.id = m.provider_id
    CROSS JOIN params
    LEFT JOIN LATERAL (
        SELECT mp.id, mp.rates, mp.currency, mp.effective_from
        FROM model_prices mp
        WHERE mp.id = pricing_effective_version(m.billing_model, 'default', NULL, now())
    ) pr ON true
    LEFT JOIN LATERAL (
        SELECT coalesce(sum(s.tokens), 0)::bigint AS tokens_30d,
               max(s.throughput_tokens_per_second) AS throughput
        FROM model_stats s
        WHERE s.model_id = m.id AND s.day >= (current_date - 30)
    ) st ON true
    -- 目录只暴露 listed。canary 是"可调用但不公开可见"，
    -- delisted 是"不可见也不可新调用"（计价 §3.6-③）。
    WHERE m.status = 'listed'
      AND ($6::text IS NULL
           OR m.display_name ILIKE '%' || $6 || '%'
           OR m.slug         ILIKE '%' || $6 || '%'
           OR p.name         ILIKE '%' || $6 || '%')
      AND ($7::text IS NULL OR p.slug = $7)
      AND (cardinality($8::text[]) = 0 OR m.modalities && $8::text[])
      AND (cardinality($9::text[]) = 0 OR m.capabilities @> $9::text[])
      AND ($10::int IS NULL
           OR m.context_length >= $10)
      AND ($11::boolean IS NULL
           OR m.zero_data_retention = $11)
      -- 价格过滤按纳美元比较。未定价（NULL）的模型在有价格上限时**被排除**：
      -- "未知"不该被当成"便宜"通过筛选。
      AND ($12::bigint IS NULL
           OR (pr.rates -> 'input' ->> 'per_million_nano')::bigint <= $12)
), keyed AS (
    SELECT base.id, base.slug, base.display_name, base.description, base.logo_url, base.modalities, base.capabilities, base.context_length, base.quality_score, base.released_at, base.billing_model, base.hosting, base.provider_id, base.provider_slug, base.provider_name, base.provider_logo_url, base.provider_model_count, base.price_version, base.stats, base.dir, base.raw_key,
           (coalesce(raw_key,
                     CASE WHEN dir = 1 THEN 'Infinity' ELSE '-Infinity' END::double precision
            ) * dir)::double precision AS sort_key,
           -- **总数要在游标过滤之前算**。放到最外层的话，翻到第二页时
           -- meta.total 会变成"剩下多少条"，而前端拿它显示"共 N 个模型"。
           count(*) OVER () AS total_count
    FROM base
)
SELECT keyed.id, keyed.slug, keyed.display_name, keyed.description, keyed.logo_url,
       keyed.modalities, keyed.capabilities, keyed.context_length, keyed.quality_score,
       keyed.released_at, keyed.billing_model, keyed.hosting,
       keyed.provider_id, keyed.provider_slug, keyed.provider_name, keyed.provider_logo_url,
       keyed.provider_model_count,
       keyed.price_version, keyed.stats, keyed.sort_key, keyed.total_count
FROM keyed
WHERE ($1::double precision IS NULL
       OR (keyed.sort_key, keyed.id) > ($1, $2::bigint))
ORDER BY keyed.sort_key, keyed.id
LIMIT $3::int
`

type ListModelsParams struct {
	CursorKey         *float64
	CursorID          int64
	RowLimit          int32
	Direction         string
	Sort              string
	Q                 *string
	Provider          *string
	Modalities        []string
	Capabilities      []string
	MinContextLength  *int32
	ZeroDataRetention *bool
	MaxInputPriceNano *int64
}

type ListModelsRow struct {
	ID                 int64
	Slug               string
	DisplayName        string
	Description        string
	LogoUrl            string
	Modalities         []string
	Capabilities       []string
	ContextLength      *int32
	QualityScore       pgtype.Numeric
	ReleasedAt         time.Time
	BillingModel       string
	Hosting            string
	ProviderID         int64
	ProviderSlug       string
	ProviderName       string
	ProviderLogoUrl    string
	ProviderModelCount int64
	PriceVersion       []byte
	Stats              []byte
	SortKey            float64
	TotalCount         int64
}

// 目录只读查询（B2）。
//
// 两条纪律贯穿本文件：
//
//  1. **价格一律通过 pricing_effective_version() 取**，没有任何查询自己写
//     "当前生效版本"的 WHERE 子句（理由见迁移里那个函数的注释，以及 M1b）。
//  2. **可空的联接结果一律用 to_jsonb() 整体带出**。价目与统计都可能不存在，
//     而"没有价目"与"价格为 0"、"没有遥测"与"吞吐为 0"在展示上是完全不同的两件事；
//     摊成一堆列会逼着每一列都取一个哨兵值，那正是 null 被当成 0 的起点。
//
// 目录列表：过滤 + 排序 + 游标分页，一条 SQL 全包。
//
// 排序键归一化成 double precision 后乘方向系数（asc=1 / desc=-1），
// 于是"两种方向 × 四种排序键"塌缩成同一个 `ORDER BY sort_key, id`，
// 游标比较也退化成一个无 NULL 的二元组比较。
// 没有价格的模型，排序键取 ±Infinity——契约写死了 **null 恒排在最后，
// 且 null ≠ 0**；把未定价的模型排成"免费"是最贵的一类展示错误。
func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]ListModelsRow, error) {
	rows, err := q.db.Query(ctx, listModels,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
		arg.Direction,
		arg.Sort,
		arg.Q,
		arg.Provider,
		arg.Modalities,
		arg.Capabilities,
		arg.MinContextLength,
		arg.ZeroDataRetention,
		arg.MaxInputPriceNano,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelsRow{}
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.LogoUrl,
			&i.Modalities,
			&i.Capabilities,
			&i.ContextLength,
			&i.QualityScore,
			&i.ReleasedAt,
			&i.BillingModel,
			&i.Hosting,
			&i.ProviderID,
			&i.ProviderSlug,
			&i.ProviderName,
			&i.ProviderLogoUrl,
			&i.ProviderModelCount,
			&i.PriceVersion,
			&i.Stats,
			&i.SortKey,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedModelIDs = `-- name: ListRelatedModelIDs :many
SELECT m.id FROM models m
WHERE m.status = 'listed' AND m.id <> $1
ORDER BY (m.provider_id = $2) DESC,
         (m.capabilities && $3::text[]) DESC,
         m.released_at DESC
LIMIT $4::int
`

type ListRelatedModelIDsParams struct {
	ModelID      int64
	ProviderID   int64
	Capabilities []string
	RowLimit     int32
}

// 同厂商优先，其次同能力。**不做"你可能还喜欢"式的推荐**：
// 那需要行为数据，而我们现在没有，猜出来的相关性会被当成事实。
func (q *Queries) ListRelatedModelIDs(ctx context.Context, arg ListRelatedModelIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRelatedModelIDs,
		arg.ModelID,
		arg.ProviderID,
		arg.Capabilities,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankModelsByColumn = `-- name: RankModelsByColumn :many
SELECT m.id,
       to_jsonb(
           CASE $1::text
               WHEN 'quality'        THEN m.quality_score::double precision
               WHEN 'context_length' THEN m.context_length::double precision
               WHEN 'throughput'     THEN st.throughput::double precision
               WHEN 'price_input'    THEN (pr.rates -> 'input' ->> 'per_million_nano')::double precision
           END
       ) AS value
FROM models m
LEFT JOIN LATERAL (
    SELECT mp.rates FROM model_prices mp
    WHERE mp.id = pricing_effective_version(m.billing_model, 'default', NULL, now())
) pr ON true
LEFT JOIN LATERAL (
    SELECT max(s.throughput_tokens_per_second) AS throughput
    FROM model_stats s
    WHERE s.model_id = m.id AND s.day >= (current_date - 30)
) st ON true
WHERE m.status = 'listed'
  AND (cardinality($2::text[]) = 0 OR m.modalities && $2::text[])
  AND ($3::boolean = false OR m.open_weights)
ORDER BY (CASE $1::text
              WHEN 'quality'        THEN m.quality_score::double precision
              WHEN 'context_length' THEN m.context_length::double precision
              WHEN 'throughput'     THEN st.throughput::double precision
              WHEN 'price_input'    THEN (pr.rates -> 'input' ->> 'per_million_nano')::double precision
          END) DESC NULLS LAST
LIMIT $4::int
`

type RankModelsByColumnParams struct {
	Metric          string
	Modalities      []string
	OpenWeightsOnly bool
	RowLimit        int32
}

type RankModelsByColumnRow struct {
	ID    int64
	Value []byte
}

// 质量分 / 吞吐 / 上下文长度 / 输入单价，四个维度共用一条查询。
// 拆成四条会让"某个维度悄悄换了口径"变得极难发现。
func (q *Queries) RankModelsByColumn(ctx context.Context, arg RankModelsByColumnParams) ([]RankModelsByColumnRow, error) {
	rows, err := q.db.Query(ctx, rankModelsByColumn,
		arg.Metric,
		arg.Modalities,
		arg.OpenWeightsOnly,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RankModelsByColumnRow{}
	for rows.Next() {
		var i RankModelsByColumnRow
		if err := rows.Scan(&i.ID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankModelsByUsage = `-- name: RankModelsByUsage :many

SELECT m.id, coalesce(sum(s.tokens), 0)::bigint AS value
FROM models m
JOIN model_stats s ON s.model_id = m.id AND s.day >= (current_date - $1::int)
WHERE m.status = 'listed'
  AND (cardinality($2::text[]) = 0 OR m.modalities && $2::text[])
  AND ($3::boolean = false OR m.open_weights)
GROUP BY m.id
HAVING coalesce(sum(s.tokens), 0) > 0
ORDER BY value DESC
LIMIT $4::int
`

type RankModelsByUsageParams struct {
	Days            int32
	Modalities      []string
	OpenWeightsOnly bool
	RowLimit        int32
}

type RankModelsByUsageRow struct {
	ID    int64
	Value int64
}

// ── 榜单 ──────────────────────────────────────────────────────
func (q *Queries) RankModelsByUsage(ctx context.Context, arg RankModelsByUsageParams) ([]RankModelsByUsageRow, error) {
	rows, err := q.db.Query(ctx, rankModelsByUsage,
		arg.Days,
		arg.Modalities,
		arg.OpenWeightsOnly,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RankModelsByUsageRow{}
	for rows.Next() {
		var i RankModelsByUsageRow
		if err := rows.Scan(&i.ID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocs = `-- name: SearchDocs :many
SELECT slug, title, description, body_markdown
FROM docs_pages
WHERE title ILIKE '%' || $1 || '%'
   OR description ILIKE '%' || $1 || '%'
   OR body_markdown ILIKE '%' || $1 || '%'
ORDER BY (title ILIKE '%' || $1 || '%') DESC, group_position, position
LIMIT $2::int
`

type SearchDocsParams struct {
	Q        *string
	RowLimit int32
}

type SearchDocsRow struct {
	Slug         string
	Title        string
	Description  string
	BodyMarkdown string
}

// ILIKE 而不是 to_tsvector：默认的分词配置对中文正文只会切出整段，
// 装 pg_jieba/zhparser 又是一个部署依赖。目录规模下 ILIKE 足够，
// 换成全文检索时这里是唯一的改动点。
func (q *Queries) SearchDocs(ctx context.Context, arg SearchDocsParams) ([]SearchDocsRow, error) {
	rows, err := q.db.Query(ctx, searchDocs, arg.Q, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocsRow{}
	for rows.Next() {
		var i SearchDocsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.BodyMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
