// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (user_id, workspace_id, role)
VALUES ($1, $2, $3)
`

type CreateMembershipParams struct {
	UserID      int64
	WorkspaceID int64
	Role        string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.UserID, arg.WorkspaceID, arg.Role)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_hash, user_id, expires_at, ip, user_agent, revoked_at, created_at
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, password_hash, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, password_hash, avatar_url, status, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash *string
	AvatarUrl    *string
}

// 手写 SQL，sqlc 生成类型安全的 Go（ARCHITECTURE.md §2.2）。
// 这个系统里最有价值的查询恰恰是最复杂的那些，ORM 在那里帮不上忙。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, plan)
VALUES ($1, $2, $3)
RETURNING id, name, slug, plan, seats_limit, balance_nano, credit_limit_nano, monthly_budget_nano, max_estimate_tokens, data_residency, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name string
	Slug string
	Plan string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.Plan)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.SeatsLimit,
		&i.BalanceNano,
		&i.CreditLimitNano,
		&i.MonthlyBudgetNano,
		&i.MaxEstimateTokens,
		&i.DataResidency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - INTERVAL '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.token_hash, s.user_id, s.expires_at, s.revoked_at, s.created_at,
       u.email, u.name, u.avatar_url, u.status
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID        int64
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	Email     string
	Name      string
	AvatarUrl *string
	Status    string
}

// 一次查询同时拿到会话与用户：会话校验在每个请求上都要跑，
// 分两次查等于把控制平面的 QPS 乘以 2。
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Status,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, avatar_url, status, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, avatar_url, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuthIdentity = `-- name: GetUserByOAuthIdentity :one
SELECT u.id, u.email, u.name, u.password_hash, u.avatar_url, u.status, u.created_at, u.updated_at FROM users u
JOIN oauth_identities oi ON oi.user_id = u.id
WHERE oi.provider = $1 AND oi.provider_uid = $2
`

type GetUserByOAuthIdentityParams struct {
	Provider    string
	ProviderUid string
}

func (q *Queries) GetUserByOAuthIdentity(ctx context.Context, arg GetUserByOAuthIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthIdentity, arg.Provider, arg.ProviderUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, plan, seats_limit, balance_nano, credit_limit_nano, monthly_budget_nano, max_estimate_tokens, data_residency, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.SeatsLimit,
		&i.BalanceNano,
		&i.CreditLimitNano,
		&i.MonthlyBudgetNano,
		&i.MaxEstimateTokens,
		&i.DataResidency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT m.user_id, m.workspace_id, m.role, m.created_at,
       w.name AS workspace_name, w.slug AS workspace_slug
FROM memberships m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.user_id = $1
ORDER BY m.created_at
`

type ListMembershipsByUserRow struct {
	UserID        int64
	WorkspaceID   int64
	Role          string
	CreatedAt     time.Time
	WorkspaceName string
	WorkspaceSlug string
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID int64) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.Role,
			&i.CreatedAt,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const upsertOAuthIdentity = `-- name: UpsertOAuthIdentity :exec
INSERT INTO oauth_identities (user_id, provider, provider_uid)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_uid) DO NOTHING
`

type UpsertOAuthIdentityParams struct {
	UserID      int64
	Provider    string
	ProviderUid string
}

func (q *Queries) UpsertOAuthIdentity(ctx context.Context, arg UpsertOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertOAuthIdentity, arg.UserID, arg.Provider, arg.ProviderUid)
	return err
}
