// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"net/netip"
	"time"
)

type AdminAccount struct {
	ID            int64
	Email         string
	Name          string
	Role          string
	PasswordHash  string
	TotpSecretEnc []byte
	TotpEnabled   bool
	CreatedBy     *int64
	LastActiveAt  *time.Time
	DisabledAt    *time.Time
	CreatedAt     time.Time
}

type AdminSession struct {
	ID        int64
	TokenHash []byte
	AdminID   int64
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
	RevokedAt *time.Time
	CreatedAt time.Time
}

type AuditLog struct {
	ID          int64
	ActorKind   string
	ActorID     *int64
	ActorLabel  string
	Action      string
	Target      string
	Destructive bool
	Detail      []byte
	Ip          *netip.Addr
	RequestID   *string
	CreatedAt   time.Time
}

type Membership struct {
	UserID      int64
	WorkspaceID int64
	Role        string
	CreatedAt   time.Time
}

type OauthIdentity struct {
	ID          int64
	UserID      int64
	Provider    string
	ProviderUid string
	CreatedAt   time.Time
}

type PlatformMetum struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

type Session struct {
	ID        int64
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
	RevokedAt *time.Time
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Email        string
	Name         string
	PasswordHash *string
	AvatarUrl    *string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Workspace struct {
	ID                int64
	Name              string
	Slug              string
	Plan              string
	SeatsLimit        int32
	BalanceNano       int64
	CreditLimitNano   int64
	MonthlyBudgetNano *int64
	MaxEstimateTokens int32
	DataResidency     string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
