// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pricing.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const closePriceVersions = `-- name: ClosePriceVersions :execrows
UPDATE model_prices
SET effective_to = $1
WHERE billing_model = $2
  AND scope_kind = $3
  AND COALESCE(scope_id, '') = COALESCE($4::text, '')
  AND effective_to IS NULL
  AND effective_from <= $1
`

type ClosePriceVersionsParams struct {
	EffectiveFrom *time.Time
	BillingModel  string
	ScopeKind     string
	ScopeID       *string
}

// 改价 = 关闭旧版本 + 插入新版本（§3.3-1）。**绝不原地 UPDATE 费率**：
// 那会让历史账单在改价当天被静默重算成另一个数字。
func (q *Queries) ClosePriceVersions(ctx context.Context, arg ClosePriceVersionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, closePriceVersions,
		arg.EffectiveFrom,
		arg.BillingModel,
		arg.ScopeKind,
		arg.ScopeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentCalls = `-- name: CountRecentCalls :one
SELECT coalesce(sum(requests), 0)::bigint            AS calls,
       coalesce(sum(input_tokens), 0)::bigint        AS input_tokens,
       coalesce(sum(output_tokens), 0)::bigint       AS output_tokens,
       coalesce(sum(upstream_cost_nano), 0)::bigint  AS upstream_cost_nano,
       coalesce(sum(charged_amount_nano), 0)::bigint AS charged_amount_nano
FROM model_stats
WHERE model_id = $1 AND day >= (current_date - 7)
`

type CountRecentCallsRow struct {
	Calls             int64
	InputTokens       int64
	OutputTokens      int64
	UpstreamCostNano  int64
	ChargedAmountNano int64
}

// "近 7 日有真实调用量"决定改价是否需要二次确认与强制 note（§3.6-⑥）。
// B3 之前 model_stats 是空的，此时返回 0 是**事实**而不是兜底。
func (q *Queries) CountRecentCalls(ctx context.Context, modelID int64) (CountRecentCallsRow, error) {
	row := q.db.QueryRow(ctx, countRecentCalls, modelID)
	var i CountRecentCallsRow
	err := row.Scan(
		&i.Calls,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UpstreamCostNano,
		&i.ChargedAmountNano,
	)
	return i, err
}

const getAdminModelByID = `-- name: GetAdminModelByID :one
SELECT m.id, m.provider_id, m.slug, m.display_name, m.description, m.logo_url, m.modalities, m.capabilities, m.context_length, m.max_output_tokens, m.architecture, m.input_formats, m.output_formats, m.supported_parameters, m.zero_data_retention, m.open_weights, m.hosting, m.billing_model, m.status, m.canary_percent, m.featured, m.featured_rank, m.quality_score, m.released_at, m.created_at, m.updated_at, p.slug AS provider_slug, p.name AS provider_name
FROM models m JOIN providers p ON p.id = m.provider_id
WHERE m.id = $1
`

type GetAdminModelByIDRow struct {
	ID                  int64
	ProviderID          int64
	Slug                string
	DisplayName         string
	Description         string
	LogoUrl             string
	Modalities          []string
	Capabilities        []string
	ContextLength       *int32
	MaxOutputTokens     *int32
	Architecture        *string
	InputFormats        []string
	OutputFormats       []string
	SupportedParameters []string
	ZeroDataRetention   bool
	OpenWeights         bool
	Hosting             string
	BillingModel        string
	Status              string
	CanaryPercent       *int32
	Featured            bool
	FeaturedRank        *int32
	QualityScore        pgtype.Numeric
	ReleasedAt          time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ProviderSlug        string
	ProviderName        string
}

func (q *Queries) GetAdminModelByID(ctx context.Context, id int64) (GetAdminModelByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminModelByID, id)
	var i GetAdminModelByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LogoUrl,
		&i.Modalities,
		&i.Capabilities,
		&i.ContextLength,
		&i.MaxOutputTokens,
		&i.Architecture,
		&i.InputFormats,
		&i.OutputFormats,
		&i.SupportedParameters,
		&i.ZeroDataRetention,
		&i.OpenWeights,
		&i.Hosting,
		&i.BillingModel,
		&i.Status,
		&i.CanaryPercent,
		&i.Featured,
		&i.FeaturedRank,
		&i.QualityScore,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderSlug,
		&i.ProviderName,
	)
	return i, err
}

const getAdminModelByPath = `-- name: GetAdminModelByPath :one
SELECT m.id, m.provider_id, m.slug, m.display_name, m.description, m.logo_url, m.modalities, m.capabilities, m.context_length, m.max_output_tokens, m.architecture, m.input_formats, m.output_formats, m.supported_parameters, m.zero_data_retention, m.open_weights, m.hosting, m.billing_model, m.status, m.canary_percent, m.featured, m.featured_rank, m.quality_score, m.released_at, m.created_at, m.updated_at, p.slug AS provider_slug, p.name AS provider_name
FROM models m JOIN providers p ON p.id = m.provider_id
WHERE p.slug = $1 AND m.slug = $2
`

type GetAdminModelByPathParams struct {
	Slug   string
	Slug_2 string
}

type GetAdminModelByPathRow struct {
	ID                  int64
	ProviderID          int64
	Slug                string
	DisplayName         string
	Description         string
	LogoUrl             string
	Modalities          []string
	Capabilities        []string
	ContextLength       *int32
	MaxOutputTokens     *int32
	Architecture        *string
	InputFormats        []string
	OutputFormats       []string
	SupportedParameters []string
	ZeroDataRetention   bool
	OpenWeights         bool
	Hosting             string
	BillingModel        string
	Status              string
	CanaryPercent       *int32
	Featured            bool
	FeaturedRank        *int32
	QualityScore        pgtype.Numeric
	ReleasedAt          time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ProviderSlug        string
	ProviderName        string
}

func (q *Queries) GetAdminModelByPath(ctx context.Context, arg GetAdminModelByPathParams) (GetAdminModelByPathRow, error) {
	row := q.db.QueryRow(ctx, getAdminModelByPath, arg.Slug, arg.Slug_2)
	var i GetAdminModelByPathRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LogoUrl,
		&i.Modalities,
		&i.Capabilities,
		&i.ContextLength,
		&i.MaxOutputTokens,
		&i.Architecture,
		&i.InputFormats,
		&i.OutputFormats,
		&i.SupportedParameters,
		&i.ZeroDataRetention,
		&i.OpenWeights,
		&i.Hosting,
		&i.BillingModel,
		&i.Status,
		&i.CanaryPercent,
		&i.Featured,
		&i.FeaturedRank,
		&i.QualityScore,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderSlug,
		&i.ProviderName,
	)
	return i, err
}

const getPriceVersionByID = `-- name: GetPriceVersionByID :one
SELECT id, billing_model, scope_kind, scope_id, currency, rates, effective_from, effective_to, source, applied_by, note, created_at FROM model_prices WHERE id = $1
`

func (q *Queries) GetPriceVersionByID(ctx context.Context, id int64) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, getPriceVersionByID, id)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.BillingModel,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Currency,
		&i.Rates,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Source,
		&i.AppliedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderBySlug = `-- name: GetProviderBySlug :one
SELECT id, slug, name, kind, logo_url, description, created_at, updated_at FROM providers WHERE slug = $1
`

func (q *Queries) GetProviderBySlug(ctx context.Context, slug string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderBySlug, slug)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModelActivity = `-- name: InsertModelActivity :exec
INSERT INTO model_activity (model_id, type, title)
VALUES ($1, $2, $3)
`

type InsertModelActivityParams struct {
	ModelID int64
	Type    string
	Title   string
}

func (q *Queries) InsertModelActivity(ctx context.Context, arg InsertModelActivityParams) error {
	_, err := q.db.Exec(ctx, insertModelActivity, arg.ModelID, arg.Type, arg.Title)
	return err
}

const insertPriceVersion = `-- name: InsertPriceVersion :one
INSERT INTO model_prices (
    billing_model, scope_kind, scope_id, currency, rates,
    effective_from, source, applied_by, note
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, billing_model, scope_kind, scope_id, currency, rates, effective_from, effective_to, source, applied_by, note, created_at
`

type InsertPriceVersionParams struct {
	BillingModel  string
	ScopeKind     string
	ScopeID       *string
	Currency      string
	Rates         []byte
	EffectiveFrom time.Time
	Source        string
	AppliedBy     string
	Note          string
}

func (q *Queries) InsertPriceVersion(ctx context.Context, arg InsertPriceVersionParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, insertPriceVersion,
		arg.BillingModel,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Currency,
		arg.Rates,
		arg.EffectiveFrom,
		arg.Source,
		arg.AppliedBy,
		arg.Note,
	)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.BillingModel,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Currency,
		&i.Rates,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Source,
		&i.AppliedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminModels = `-- name: ListAdminModels :many
SELECT m.id, m.provider_id, m.slug, m.display_name, m.description, m.logo_url, m.modalities, m.capabilities, m.context_length, m.max_output_tokens, m.architecture, m.input_formats, m.output_formats, m.supported_parameters, m.zero_data_retention, m.open_weights, m.hosting, m.billing_model, m.status, m.canary_percent, m.featured, m.featured_rank, m.quality_score, m.released_at, m.created_at, m.updated_at, p.slug AS provider_slug, p.name AS provider_name,
       to_jsonb(pv.id) AS price_version_id,
       (SELECT coalesce(sum(s.requests), 0)::bigint FROM model_stats s
         WHERE s.model_id = m.id AND s.day >= (current_date - 7)) AS calls_last_7d
FROM models m JOIN providers p ON p.id = m.provider_id
LEFT JOIN LATERAL (
    SELECT pricing_effective_version(m.billing_model, 'default', NULL, now()) AS id
) pv ON true
WHERE $1::text IS NULL OR m.status = $1
ORDER BY p.slug, m.slug
`

type ListAdminModelsRow struct {
	ID                  int64
	ProviderID          int64
	Slug                string
	DisplayName         string
	Description         string
	LogoUrl             string
	Modalities          []string
	Capabilities        []string
	ContextLength       *int32
	MaxOutputTokens     *int32
	Architecture        *string
	InputFormats        []string
	OutputFormats       []string
	SupportedParameters []string
	ZeroDataRetention   bool
	OpenWeights         bool
	Hosting             string
	BillingModel        string
	Status              string
	CanaryPercent       *int32
	Featured            bool
	FeaturedRank        *int32
	QualityScore        pgtype.Numeric
	ReleasedAt          time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ProviderSlug        string
	ProviderName        string
	PriceVersionID      []byte
	CallsLast7d         int64
}

// admin 看得到全部四态；web 只看得到 listed。
// price_version_id 走 LEFT JOIN LATERAL 而不是直接调用函数：直接调用会被
// sqlc 推断成 NOT NULL bigint（函数签名如此），draft 模型没有价目时
// 会在扫描阶段报 "cannot scan NULL into *int64"——这条路径只有在真的存在
// 一个没有价目的模型时才会被触发，冒烟测试的种子数据没覆盖到就会漏网。
func (q *Queries) ListAdminModels(ctx context.Context, status *string) ([]ListAdminModelsRow, error) {
	rows, err := q.db.Query(ctx, listAdminModels, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminModelsRow{}
	for rows.Next() {
		var i ListAdminModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.LogoUrl,
			&i.Modalities,
			&i.Capabilities,
			&i.ContextLength,
			&i.MaxOutputTokens,
			&i.Architecture,
			&i.InputFormats,
			&i.OutputFormats,
			&i.SupportedParameters,
			&i.ZeroDataRetention,
			&i.OpenWeights,
			&i.Hosting,
			&i.BillingModel,
			&i.Status,
			&i.CanaryPercent,
			&i.Featured,
			&i.FeaturedRank,
			&i.QualityScore,
			&i.ReleasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderSlug,
			&i.ProviderName,
			&i.PriceVersionID,
			&i.CallsLast7d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceVersions = `-- name: ListPriceVersions :many
SELECT id, billing_model, scope_kind, scope_id, currency, rates, effective_from, effective_to, source, applied_by, note, created_at FROM model_prices
WHERE billing_model = $1
ORDER BY effective_from DESC
LIMIT $2
`

type ListPriceVersionsParams struct {
	BillingModel string
	Limit        int32
}

func (q *Queries) ListPriceVersions(ctx context.Context, arg ListPriceVersionsParams) ([]ModelPrice, error) {
	rows, err := q.db.Query(ctx, listPriceVersions, arg.BillingModel, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPrice{}
	for rows.Next() {
		var i ModelPrice
		if err := rows.Scan(
			&i.ID,
			&i.BillingModel,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Currency,
			&i.Rates,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Source,
			&i.AppliedBy,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePriceVersion = `-- name: ResolvePriceVersion :one

SELECT mp.id, mp.billing_model, mp.scope_kind, mp.scope_id, mp.currency, mp.rates, mp.effective_from, mp.effective_to, mp.source, mp.applied_by, mp.note, mp.created_at FROM model_prices mp
WHERE mp.id = coalesce(
    pricing_effective_version($1,          'workspace', $2::text, $3),
    pricing_effective_version($1,          'plan',      $4::text,         $3),
    pricing_effective_version($1,          'default',   NULL,                            $3),
    pricing_effective_version($5, 'default',   NULL,                            $3)
)
`

type ResolvePriceVersionParams struct {
	BillingModel         string
	WorkspaceID          *string
	At                   time.Time
	Plan                 *string
	FallbackBillingModel string
}

// 价目查询（M1 / M1a / M1b）。
//
// **本文件是价目的唯一 SQL 入口。** catalog 侧只在 catalog.sql 里通过同一个
// pricing_effective_version() 取默认档价格用于排序过滤，展示与结算的费率解析
// 都走 internal/pricing 的同一个 Go 函数（计价 §3.6-②）。
// 价目解析的**唯一实现**。四层优先级（计价 §3.4）：
//
//	workspace 专属协议价 > plan 价目 > 计费别名默认价 > 模型默认价
//
// 每一层是**整体覆盖**，不是字段级合并。字段级合并看起来灵活，
// 实际会产生"没人能说清这个模型现在多少钱"的价目，排查成本极高。
//
// at 由调用方给：结算必须传 RequestContext.ReceivedAt 而不是 now()，
// 否则一次跨越改价时刻的长流会中途换价（§3.3-3）。
func (q *Queries) ResolvePriceVersion(ctx context.Context, arg ResolvePriceVersionParams) (ModelPrice, error) {
	row := q.db.QueryRow(ctx, resolvePriceVersion,
		arg.BillingModel,
		arg.WorkspaceID,
		arg.At,
		arg.Plan,
		arg.FallbackBillingModel,
	)
	var i ModelPrice
	err := row.Scan(
		&i.ID,
		&i.BillingModel,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Currency,
		&i.Rates,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Source,
		&i.AppliedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const setModelStatus = `-- name: SetModelStatus :one
UPDATE models
SET status = $2, canary_percent = $3, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, slug, display_name, description, logo_url, modalities, capabilities, context_length, max_output_tokens, architecture, input_formats, output_formats, supported_parameters, zero_data_retention, open_weights, hosting, billing_model, status, canary_percent, featured, featured_rank, quality_score, released_at, created_at, updated_at
`

type SetModelStatusParams struct {
	ID            int64
	Status        string
	CanaryPercent *int32
}

func (q *Queries) SetModelStatus(ctx context.Context, arg SetModelStatusParams) (Model, error) {
	row := q.db.QueryRow(ctx, setModelStatus, arg.ID, arg.Status, arg.CanaryPercent)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LogoUrl,
		&i.Modalities,
		&i.Capabilities,
		&i.ContextLength,
		&i.MaxOutputTokens,
		&i.Architecture,
		&i.InputFormats,
		&i.OutputFormats,
		&i.SupportedParameters,
		&i.ZeroDataRetention,
		&i.OpenWeights,
		&i.Hosting,
		&i.BillingModel,
		&i.Status,
		&i.CanaryPercent,
		&i.Featured,
		&i.FeaturedRank,
		&i.QualityScore,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertModel = `-- name: UpsertModel :one
INSERT INTO models (
    provider_id, slug, display_name, description, logo_url,
    modalities, capabilities, context_length, max_output_tokens,
    architecture, input_formats, output_formats, supported_parameters,
    zero_data_retention, open_weights, hosting, billing_model, released_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (provider_id, slug) DO UPDATE
SET display_name = excluded.display_name,
    description = excluded.description,
    logo_url = excluded.logo_url,
    modalities = excluded.modalities,
    capabilities = excluded.capabilities,
    context_length = excluded.context_length,
    max_output_tokens = excluded.max_output_tokens,
    architecture = excluded.architecture,
    input_formats = excluded.input_formats,
    output_formats = excluded.output_formats,
    supported_parameters = excluded.supported_parameters,
    zero_data_retention = excluded.zero_data_retention,
    open_weights = excluded.open_weights,
    hosting = excluded.hosting,
    billing_model = excluded.billing_model,
    updated_at = now()
RETURNING id, provider_id, slug, display_name, description, logo_url, modalities, capabilities, context_length, max_output_tokens, architecture, input_formats, output_formats, supported_parameters, zero_data_retention, open_weights, hosting, billing_model, status, canary_percent, featured, featured_rank, quality_score, released_at, created_at, updated_at
`

type UpsertModelParams struct {
	ProviderID          int64
	Slug                string
	DisplayName         string
	Description         string
	LogoUrl             string
	Modalities          []string
	Capabilities        []string
	ContextLength       *int32
	MaxOutputTokens     *int32
	Architecture        *string
	InputFormats        []string
	OutputFormats       []string
	SupportedParameters []string
	ZeroDataRetention   bool
	OpenWeights         bool
	Hosting             string
	BillingModel        string
	ReleasedAt          time.Time
}

// **status 不在 SET 列表里**：发布/下架是独立的、要校验价目完整性的动作，
// 不能被一次元数据编辑顺手带过去（计价 §3.6-③）。
func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, upsertModel,
		arg.ProviderID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.LogoUrl,
		arg.Modalities,
		arg.Capabilities,
		arg.ContextLength,
		arg.MaxOutputTokens,
		arg.Architecture,
		arg.InputFormats,
		arg.OutputFormats,
		arg.SupportedParameters,
		arg.ZeroDataRetention,
		arg.OpenWeights,
		arg.Hosting,
		arg.BillingModel,
		arg.ReleasedAt,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LogoUrl,
		&i.Modalities,
		&i.Capabilities,
		&i.ContextLength,
		&i.MaxOutputTokens,
		&i.Architecture,
		&i.InputFormats,
		&i.OutputFormats,
		&i.SupportedParameters,
		&i.ZeroDataRetention,
		&i.OpenWeights,
		&i.Hosting,
		&i.BillingModel,
		&i.Status,
		&i.CanaryPercent,
		&i.Featured,
		&i.FeaturedRank,
		&i.QualityScore,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProvider = `-- name: UpsertProvider :one

INSERT INTO providers (slug, name, kind, logo_url, description)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (slug) DO UPDATE
SET name = excluded.name, kind = excluded.kind,
    logo_url = excluded.logo_url, description = excluded.description,
    updated_at = now()
RETURNING id, slug, name, kind, logo_url, description, created_at, updated_at
`

type UpsertProviderParams struct {
	Slug        string
	Name        string
	Kind        string
	LogoUrl     string
	Description string
}

// ── admin 写入口（M1a）─────────────────────────────────────────
func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, upsertProvider,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.LogoUrl,
		arg.Description,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
