// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	CountAdmins(ctx context.Context) (int64, error)
	// 平台管理员。与 users 完全独立的一套（ARCHITECTURE.md §4.5）。
	CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (AdminAccount, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// 手写 SQL，sqlc 生成类型安全的 Go（ARCHITECTURE.md §2.2）。
	// 这个系统里最有价值的查询恰恰是最复杂的那些，ORM 在那里帮不上忙。
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	// 停用而非删除：审计日志里的 actor 要能一直解析出人名。
	DisableAdmin(ctx context.Context, id int64) error
	GetAdminByEmail(ctx context.Context, lower string) (AdminAccount, error)
	GetAdminByID(ctx context.Context, id int64) (AdminAccount, error)
	GetAdminSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAdminSessionByTokenHashRow, error)
	// 一次查询同时拿到会话与用户：会话校验在每个请求上都要跑，
	// 分两次查等于把控制平面的 QPS 乘以 2。
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByOAuthIdentity(ctx context.Context, arg GetUserByOAuthIdentityParams) (User, error)
	GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAdmins(ctx context.Context) ([]AdminAccount, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListMembershipsByUser(ctx context.Context, userID int64) ([]ListMembershipsByUserRow, error)
	RevokeAdminSession(ctx context.Context, tokenHash []byte) error
	RevokeAllAdminSessions(ctx context.Context, adminID int64) error
	RevokeAllUserSessions(ctx context.Context, userID int64) error
	RevokeSession(ctx context.Context, tokenHash []byte) error
	SetAdminTOTP(ctx context.Context, arg SetAdminTOTPParams) error
	TouchAdminActivity(ctx context.Context, id int64) error
	UpsertOAuthIdentity(ctx context.Context, arg UpsertOAuthIdentityParams) error
}

var _ Querier = (*Queries)(nil)
