// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: routing.sql

package dbgen

import (
	"context"
	"time"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (provider_profile_id, name, base_url_override, credentials_enc,
                      region, priority, weight, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, provider_profile_id, name, base_url_override, credentials_enc, region, priority, weight, status, health_alpha, health_beta, latency_ema_ms, consecutive_failures, rate_limited_until, probe_interval_seconds, last_probe_at, created_at, updated_at
`

type CreateChannelParams struct {
	ProviderProfileID int64
	Name              string
	BaseUrlOverride   *string
	CredentialsEnc    []byte
	Region            string
	Priority          int32
	Weight            int32
	Status            string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ProviderProfileID,
		arg.Name,
		arg.BaseUrlOverride,
		arg.CredentialsEnc,
		arg.Region,
		arg.Priority,
		arg.Weight,
		arg.Status,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProviderProfileID,
		&i.Name,
		&i.BaseUrlOverride,
		&i.CredentialsEnc,
		&i.Region,
		&i.Priority,
		&i.Weight,
		&i.Status,
		&i.HealthAlpha,
		&i.HealthBeta,
		&i.LatencyEmaMs,
		&i.ConsecutiveFailures,
		&i.RateLimitedUntil,
		&i.ProbeIntervalSeconds,
		&i.LastProbeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT c.id, c.provider_profile_id, c.name, c.base_url_override, c.credentials_enc, c.region, c.priority, c.weight, c.status, c.health_alpha, c.health_beta, c.latency_ema_ms, c.consecutive_failures, c.rate_limited_until, c.probe_interval_seconds, c.last_probe_at, c.created_at, c.updated_at, p.slug AS provider_slug, p.protocol, p.base_url AS provider_base_url,
       p.auth_scheme, p.auth_header, p.quirks
FROM channels c JOIN provider_profiles p ON p.id = c.provider_profile_id
WHERE c.id = $1
`

type GetChannelByIDRow struct {
	ID                   int64
	ProviderProfileID    int64
	Name                 string
	BaseUrlOverride      *string
	CredentialsEnc       []byte
	Region               string
	Priority             int32
	Weight               int32
	Status               string
	HealthAlpha          float64
	HealthBeta           float64
	LatencyEmaMs         *float64
	ConsecutiveFailures  int32
	RateLimitedUntil     *time.Time
	ProbeIntervalSeconds int32
	LastProbeAt          *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderSlug         string
	Protocol             string
	ProviderBaseUrl      string
	AuthScheme           string
	AuthHeader           string
	Quirks               []byte
}

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (GetChannelByIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i GetChannelByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderProfileID,
		&i.Name,
		&i.BaseUrlOverride,
		&i.CredentialsEnc,
		&i.Region,
		&i.Priority,
		&i.Weight,
		&i.Status,
		&i.HealthAlpha,
		&i.HealthBeta,
		&i.LatencyEmaMs,
		&i.ConsecutiveFailures,
		&i.RateLimitedUntil,
		&i.ProbeIntervalSeconds,
		&i.LastProbeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderSlug,
		&i.Protocol,
		&i.ProviderBaseUrl,
		&i.AuthScheme,
		&i.AuthHeader,
		&i.Quirks,
	)
	return i, err
}

const getProbeChannelModel = `-- name: GetProbeChannelModel :one
SELECT cm.model_id, cm.upstream_model_name, m.billing_model
FROM channel_models cm
JOIN models m ON m.id = cm.model_id
WHERE cm.channel_id = $1 AND cm.is_probe = true AND cm.enabled = true
LIMIT 1
`

type GetProbeChannelModelRow struct {
	ModelID           int64
	UpstreamModelName string
	BillingModel      string
}

// 手工连通性测试选模型的优先级第二档：该渠道标了 is_probe 的模型
// （UNIFIED §5.6-①）。第一档"admin 显式指定"与第三档"近 7 日调用量最高"
// 由调用方在 Go 侧决定，不是每一档都值得写成 SQL。
func (q *Queries) GetProbeChannelModel(ctx context.Context, channelID int64) (GetProbeChannelModelRow, error) {
	row := q.db.QueryRow(ctx, getProbeChannelModel, channelID)
	var i GetProbeChannelModelRow
	err := row.Scan(&i.ModelID, &i.UpstreamModelName, &i.BillingModel)
	return i, err
}

const listCandidateChannels = `-- name: ListCandidateChannels :many
SELECT
    c.id AS channel_id, c.name AS channel_name, c.provider_profile_id,
    c.priority, c.weight, c.health_alpha, c.health_beta, c.latency_ema_ms,
    c.rate_limited_until, c.consecutive_failures, c.probe_interval_seconds, c.last_probe_at,
    c.credentials_enc, c.base_url_override,
    p.slug AS provider_slug, p.protocol, p.base_url AS provider_base_url,
    p.auth_scheme, p.auth_header, p.quirks,
    cm.upstream_model_name, cm.priority_override, cm.weight_override
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
JOIN provider_profiles p ON p.id = c.provider_profile_id
WHERE cm.model_id = $1 AND cm.enabled = true AND c.status = 'active'
`

type ListCandidateChannelsRow struct {
	ChannelID            int64
	ChannelName          string
	ProviderProfileID    int64
	Priority             int32
	Weight               int32
	HealthAlpha          float64
	HealthBeta           float64
	LatencyEmaMs         *float64
	RateLimitedUntil     *time.Time
	ConsecutiveFailures  int32
	ProbeIntervalSeconds int32
	LastProbeAt          *time.Time
	CredentialsEnc       []byte
	BaseUrlOverride      *string
	ProviderSlug         string
	Protocol             string
	ProviderBaseUrl      string
	AuthScheme           string
	AuthHeader           string
	Quirks               []byte
	UpstreamModelName    string
	PriorityOverride     *int32
	WeightOverride       *int32
}

// 一个模型的全部候选渠道（B3/P3 的路由热路径）。
// 复合索引 (model_id, enabled) 已经建在 channel_models 上；渠道状态与
// 限流窗口在这里一并过滤，避免路由代码里再判断一次。
func (q *Queries) ListCandidateChannels(ctx context.Context, modelID int64) ([]ListCandidateChannelsRow, error) {
	rows, err := q.db.Query(ctx, listCandidateChannels, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidateChannelsRow{}
	for rows.Next() {
		var i ListCandidateChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.ProviderProfileID,
			&i.Priority,
			&i.Weight,
			&i.HealthAlpha,
			&i.HealthBeta,
			&i.LatencyEmaMs,
			&i.RateLimitedUntil,
			&i.ConsecutiveFailures,
			&i.ProbeIntervalSeconds,
			&i.LastProbeAt,
			&i.CredentialsEnc,
			&i.BaseUrlOverride,
			&i.ProviderSlug,
			&i.Protocol,
			&i.ProviderBaseUrl,
			&i.AuthScheme,
			&i.AuthHeader,
			&i.Quirks,
			&i.UpstreamModelName,
			&i.PriorityOverride,
			&i.WeightOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsDueForProbe = `-- name: ListChannelsDueForProbe :many
SELECT id, consecutive_failures, probe_interval_seconds
FROM channels
WHERE status = 'active'
  AND (last_probe_at IS NULL OR last_probe_at < now() - (probe_interval_seconds || ' seconds')::interval)
`

type ListChannelsDueForProbeRow struct {
	ID                   int64
	ConsecutiveFailures  int32
	ProbeIntervalSeconds int32
}

func (q *Queries) ListChannelsDueForProbe(ctx context.Context) ([]ListChannelsDueForProbeRow, error) {
	rows, err := q.db.Query(ctx, listChannelsDueForProbe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsDueForProbeRow{}
	for rows.Next() {
		var i ListChannelsDueForProbeRow
		if err := rows.Scan(&i.ID, &i.ConsecutiveFailures, &i.ProbeIntervalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordChannelFailure = `-- name: RecordChannelFailure :exec
UPDATE channels
SET health_beta = health_beta + 1,
    consecutive_failures = consecutive_failures + 1,
    rate_limited_until = CASE WHEN $1::boolean
                               THEN now() + ($2::int || ' seconds')::interval
                               ELSE rate_limited_until END,
    updated_at = now()
WHERE id = $3
`

type RecordChannelFailureParams struct {
	RateLimited      bool
	RateLimitSeconds int32
	ID               int64
}

// Beta 后验更新：一次失败 = beta+1。429 时额外设置限流窗口
// （rateLimitFactor 的输入，UNIFIED §5.5 的乘性护栏）。
func (q *Queries) RecordChannelFailure(ctx context.Context, arg RecordChannelFailureParams) error {
	_, err := q.db.Exec(ctx, recordChannelFailure, arg.RateLimited, arg.RateLimitSeconds, arg.ID)
	return err
}

const recordChannelSuccess = `-- name: RecordChannelSuccess :exec
UPDATE channels
SET health_alpha = health_alpha + 1,
    consecutive_failures = 0,
    latency_ema_ms = CASE
        WHEN latency_ema_ms IS NULL THEN $1::double precision
        ELSE latency_ema_ms * 0.7 + $1::double precision * 0.3
    END,
    updated_at = now()
WHERE id = $2
`

type RecordChannelSuccessParams struct {
	LatencyMs float64
	ID        int64
}

// Beta 后验更新：一次成功 = alpha+1。同时把限流窗口清掉、连续失败清零、
// 更新延迟 EMA（平滑系数 0.3，足够快地反映最近状况又不被单次抖动带偏）。
func (q *Queries) RecordChannelSuccess(ctx context.Context, arg RecordChannelSuccessParams) error {
	_, err := q.db.Exec(ctx, recordChannelSuccess, arg.LatencyMs, arg.ID)
	return err
}

const resolveRoutingPolicy = `-- name: ResolveRoutingPolicy :one

SELECT id, name, scope_kind, scope_id, strategy, weights, fallback_depth, updated_by, updated_at FROM routing_policies
WHERE (scope_kind = 'model'     AND scope_id IS NOT DISTINCT FROM $1::text)
   OR (scope_kind = 'workspace' AND scope_id IS NOT DISTINCT FROM $2::text)
   OR (scope_kind = 'global'    AND scope_id IS NULL)
ORDER BY CASE scope_kind WHEN 'model' THEN 0 WHEN 'workspace' THEN 1 ELSE 2 END
LIMIT 1
`

type ResolveRoutingPolicyParams struct {
	ModelID     *string
	WorkspaceID *string
}

// ── 路由策略（X9）───────────────────────────────────────────────
// 解析顺序 model > workspace > global，整体覆盖（计价 §3.4 同一原则）。
//
// **不能写成 `(scope_kind, scope_id) IN ((...), (...), ('global', NULL))`**：
// SQL 的行比较里只要有一个分量是 NULL，整行比较结果就是 UNKNOWN 而不是
// TRUE——即使目标行的 scope_id 也是 NULL。用这种写法时 scope_kind='global'
// 的策略永远匹配不到，会静默退回调用方的默认值（这里是 balanced），
// 而不是报错，因此第一次真实验证时才会暴露。改用显式的 OR + IS NOT
// DISTINCT FROM，它对 NULL 的语义是"两边都是 NULL 时也算相等"。
func (q *Queries) ResolveRoutingPolicy(ctx context.Context, arg ResolveRoutingPolicyParams) (RoutingPolicy, error) {
	row := q.db.QueryRow(ctx, resolveRoutingPolicy, arg.ModelID, arg.WorkspaceID)
	var i RoutingPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Strategy,
		&i.Weights,
		&i.FallbackDepth,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const touchChannelProbe = `-- name: TouchChannelProbe :exec
UPDATE channels
SET last_probe_at = now(), probe_interval_seconds = $2
WHERE id = $1
`

type TouchChannelProbeParams struct {
	ID                   int64
	ProbeIntervalSeconds int32
}

// 探针退休（§5.5 末段）：连续失败越多，下一次自动探测的间隔越长，
// 上限由调用方算好传入——避免对已死的上游持续打无效请求。
func (q *Queries) TouchChannelProbe(ctx context.Context, arg TouchChannelProbeParams) error {
	_, err := q.db.Exec(ctx, touchChannelProbe, arg.ID, arg.ProbeIntervalSeconds)
	return err
}

const upsertChannelModel = `-- name: UpsertChannelModel :exec
INSERT INTO channel_models (channel_id, model_id, upstream_model_name, enabled,
                            priority_override, weight_override, is_probe)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (channel_id, model_id) DO UPDATE
SET upstream_model_name = excluded.upstream_model_name, enabled = excluded.enabled,
    priority_override = excluded.priority_override, weight_override = excluded.weight_override,
    is_probe = excluded.is_probe
`

type UpsertChannelModelParams struct {
	ChannelID         int64
	ModelID           int64
	UpstreamModelName string
	Enabled           bool
	PriorityOverride  *int32
	WeightOverride    *int32
	IsProbe           bool
}

func (q *Queries) UpsertChannelModel(ctx context.Context, arg UpsertChannelModelParams) error {
	_, err := q.db.Exec(ctx, upsertChannelModel,
		arg.ChannelID,
		arg.ModelID,
		arg.UpstreamModelName,
		arg.Enabled,
		arg.PriorityOverride,
		arg.WeightOverride,
		arg.IsProbe,
	)
	return err
}

const upsertProviderProfile = `-- name: UpsertProviderProfile :one

INSERT INTO provider_profiles (slug, name, protocol, base_url, auth_scheme, auth_header, quirks)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug) DO UPDATE
SET name = excluded.name, protocol = excluded.protocol, base_url = excluded.base_url,
    auth_scheme = excluded.auth_scheme, auth_header = excluded.auth_header,
    quirks = excluded.quirks, updated_at = now()
RETURNING id, slug, name, protocol, base_url, auth_scheme, auth_header, quirks, created_at, updated_at
`

type UpsertProviderProfileParams struct {
	Slug       string
	Name       string
	Protocol   string
	BaseUrl    string
	AuthScheme string
	AuthHeader string
	Quirks     []byte
}

// 供给与路由（I4：P2/P3/B4/X9/X10）。
func (q *Queries) UpsertProviderProfile(ctx context.Context, arg UpsertProviderProfileParams) (ProviderProfile, error) {
	row := q.db.QueryRow(ctx, upsertProviderProfile,
		arg.Slug,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.AuthScheme,
		arg.AuthHeader,
		arg.Quirks,
	)
	var i ProviderProfile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.AuthHeader,
		&i.Quirks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRoutingPolicy = `-- name: UpsertRoutingPolicy :one
INSERT INTO routing_policies (name, scope_kind, scope_id, strategy, weights, fallback_depth, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (scope_kind, COALESCE(scope_id, '')) DO UPDATE
SET name = excluded.name, strategy = excluded.strategy, weights = excluded.weights,
    fallback_depth = excluded.fallback_depth, updated_by = excluded.updated_by, updated_at = now()
RETURNING id, name, scope_kind, scope_id, strategy, weights, fallback_depth, updated_by, updated_at
`

type UpsertRoutingPolicyParams struct {
	Name          string
	ScopeKind     string
	ScopeID       *string
	Strategy      string
	Weights       []byte
	FallbackDepth int32
	UpdatedBy     string
}

func (q *Queries) UpsertRoutingPolicy(ctx context.Context, arg UpsertRoutingPolicyParams) (RoutingPolicy, error) {
	row := q.db.QueryRow(ctx, upsertRoutingPolicy,
		arg.Name,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Strategy,
		arg.Weights,
		arg.FallbackDepth,
		arg.UpdatedBy,
	)
	var i RoutingPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Strategy,
		&i.Weights,
		&i.FallbackDepth,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
