// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: seed.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const setModelPresentation = `-- name: SetModelPresentation :exec

UPDATE models
SET featured = $2, featured_rank = $3, quality_score = $4, updated_at = now()
WHERE id = $1
`

type SetModelPresentationParams struct {
	ID           int64
	Featured     bool
	FeaturedRank *int32
	QualityScore pgtype.Numeric
}

// 开发种子数据的写入（`umaas seed catalog`）。
//
// **这些查询只服务开发环境**，seed 命令在 env=prod 时直接拒绝执行。
// 它们写的都是"展示层属性"（精选位、质量分、评测结果、文档），
// 唯独不写价目——价目只能走 pricing.sql 的那条路径（计价 §3.6-①）。
func (q *Queries) SetModelPresentation(ctx context.Context, arg SetModelPresentationParams) error {
	_, err := q.db.Exec(ctx, setModelPresentation,
		arg.ID,
		arg.Featured,
		arg.FeaturedRank,
		arg.QualityScore,
	)
	return err
}

const upsertBenchmark = `-- name: UpsertBenchmark :one
INSERT INTO benchmarks (slug, name, category, description, methodology,
                        configuration, run_count, last_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (slug) DO UPDATE
SET name = excluded.name, category = excluded.category,
    description = excluded.description, methodology = excluded.methodology,
    configuration = excluded.configuration, run_count = excluded.run_count,
    last_run_at = excluded.last_run_at
RETURNING id
`

type UpsertBenchmarkParams struct {
	Slug          string
	Name          string
	Category      string
	Description   string
	Methodology   string
	Configuration []byte
	RunCount      int32
	LastRunAt     *time.Time
}

func (q *Queries) UpsertBenchmark(ctx context.Context, arg UpsertBenchmarkParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBenchmark,
		arg.Slug,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Methodology,
		arg.Configuration,
		arg.RunCount,
		arg.LastRunAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertBenchmarkResult = `-- name: UpsertBenchmarkResult :exec
INSERT INTO benchmark_results (benchmark_id, model_id, score, percentile,
                               cost_nano, duration_ms, sample_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (benchmark_id, model_id) DO UPDATE
SET score = excluded.score, percentile = excluded.percentile,
    cost_nano = excluded.cost_nano, duration_ms = excluded.duration_ms,
    sample_count = excluded.sample_count, run_at = now()
`

type UpsertBenchmarkResultParams struct {
	BenchmarkID int64
	ModelID     int64
	Score       pgtype.Numeric
	Percentile  pgtype.Numeric
	CostNano    int64
	DurationMs  pgtype.Numeric
	SampleCount int32
}

func (q *Queries) UpsertBenchmarkResult(ctx context.Context, arg UpsertBenchmarkResultParams) error {
	_, err := q.db.Exec(ctx, upsertBenchmarkResult,
		arg.BenchmarkID,
		arg.ModelID,
		arg.Score,
		arg.Percentile,
		arg.CostNano,
		arg.DurationMs,
		arg.SampleCount,
	)
	return err
}

const upsertDocsPage = `-- name: UpsertDocsPage :exec
INSERT INTO docs_pages (slug, group_title, group_position, position,
                        title, description, badge, body_markdown, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (slug) DO UPDATE
SET group_title = excluded.group_title, group_position = excluded.group_position,
    position = excluded.position, title = excluded.title,
    description = excluded.description, badge = excluded.badge,
    body_markdown = excluded.body_markdown, updated_at = now()
`

type UpsertDocsPageParams struct {
	Slug          string
	GroupTitle    string
	GroupPosition int32
	Position      int32
	Title         string
	Description   string
	Badge         string
	BodyMarkdown  string
}

func (q *Queries) UpsertDocsPage(ctx context.Context, arg UpsertDocsPageParams) error {
	_, err := q.db.Exec(ctx, upsertDocsPage,
		arg.Slug,
		arg.GroupTitle,
		arg.GroupPosition,
		arg.Position,
		arg.Title,
		arg.Description,
		arg.Badge,
		arg.BodyMarkdown,
	)
	return err
}

const upsertModelFAQ = `-- name: UpsertModelFAQ :exec
INSERT INTO model_faq (model_id, question, answer, position)
SELECT $1, $2, $3, $4
WHERE NOT EXISTS (
    SELECT 1 FROM model_faq WHERE model_id = $1 AND question = $2
)
`

type UpsertModelFAQParams struct {
	ModelID  int64
	Question string
	Answer   string
	Position int32
}

func (q *Queries) UpsertModelFAQ(ctx context.Context, arg UpsertModelFAQParams) error {
	_, err := q.db.Exec(ctx, upsertModelFAQ,
		arg.ModelID,
		arg.Question,
		arg.Answer,
		arg.Position,
	)
	return err
}
